logging:
  file: ./sc06.log
  level:
    root: info
    cn: debug
server:
  port: 8086
  context-path: /config
spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: git@192.168.1.241:/home/git/test.git
          clone-on-start: true
          force-pull: true
          search-paths: config_guiyang
          default-label: master
          strict-host-key-checking: false
          ignore-local-ssh-settings: true
          basedir: f:/111/
          private-key:  |
                        -----BEGIN RSA PRIVATE KEY-----
                        MIIEogIBAAKCAQEAwcwePcwk97aYMYhUMMHhOaU4JX5w8QfdJdZY8z7hmj+WHKOv
                        mYzbB7j0UUVRMh6OvUeJ/VjpkPlwfDAfvVRq0QKNYaaR1IANl7AaGA3Gm6dSJ56t
                        MpJFe63FFvFCia75AQ0+t72pUqcy2dJA93WhjxhWpx6ae+M5V6i00/pjRbYXGbeC
                        Ji0HeEboJZpqZtMv+jGuS4wj/LwIlmwYkAE28x+zKND+Fn6lG6I=
                        -----END RSA PRIVATE KEY-----
          