logging:
  file: ./sb09_all.log
  level:
    root: info
    cn: debug
spring:
  application:
    name: sb09_logback
  kafka:
    client-id: 1_${spring.application.name}_${server.port}
    bootstrap-servers: 192.168.1.236:9092
    consumer:
      bootstrap-servers: 192.168.1.236:9092
      client-id: 1_${spring.application.name}_${server.port}
      group-id: test_group
server:
  port: 8089