logging:
  file: ./sc01_${random.value:00}.log
  level:
    root: info
    cn: debug
server:
  port: 8082
spring:
  application:
    name: spring-cloud-eureka
  profiles: server2
eureka:
  instance:
    preferIpAddress: true
    ip-address: 192.168.1.241
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://192.168.1.241:8081/eureka/