logging:
  file: ./sc02_${random.int[1000,9999]}.log
  level:
    root: info
    cn: debug
server:
  port: 8082
spring:
  application:
    name: spring-cloud-eureka-producer
  cloud:
    inetutils:
      ignored-interfaces: ethx
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://192.168.1.241:8087
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    preferIpAddress: true
    ip-address: ${spring.cloud.client.ipAddress}
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.1.241:9000/eureka/