logging:
  file: ./sc07.log
  level:
    root: info
    cn: debug
server:
  port: 8087
spring:
  application:
    name: spring-cloud-zipkein-server
  cloud:
    inetutils:
      ignored-interfaces: ethx
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    preferIpAddress: true
    ip-address: ${spring.cloud.client.ipAddress}
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.1.241:9000/eureka/