package cn.xz.entity;
// Generated Jan 9, 2018 11:30:28 AM by Hibernate Tools 5.2.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CloudUserInfo generated by hbm2java
 */
@Entity
@Table(name = "cloud_user_info", catalog = "hce_guiyang")
public class CloudUserInfo implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -6452663887770367038L;
    private String userId;
    private String imei;
    private String onlineMoney;
    private String consumeKey;
    private String tacKey;
    private Integer type;
    private String addTime;
    private String modTime;
    private String cardSeq;
    private String cardNo;
    private Short status;
    private String file15;
    private String file17;
    private Short istest;
    private String phonemodel;
    private Short credit;
    private Short phoneType;

    public CloudUserInfo() {
    }

    @Override
    public String toString() {
        return "CloudUserInfo [userId=" + userId + ", imei=" + imei + ", onlineMoney=" + onlineMoney + ", consumeKey="
                + consumeKey + ", tacKey=" + tacKey + ", type=" + type + ", addTime=" + addTime + ", modTime=" + modTime
                + ", cardSeq=" + cardSeq + ", cardNo=" + cardNo + ", status=" + status + ", file15=" + file15
                + ", file17=" + file17 + ", istest=" + istest + ", phonemodel=" + phonemodel + ", credit=" + credit
                + ", phoneType=" + phoneType + "]";
    }

    public CloudUserInfo(String userId, String onlineMoney) {
        this.userId = userId;
        this.onlineMoney = onlineMoney;
    }

    public CloudUserInfo(String userId, String imei, String onlineMoney, String consumeKey, String tacKey, Integer type,
            String addTime, String modTime, String cardSeq, String cardNo, Short status, String file15, String file17,
            Short istest, String phonemodel, Short credit, Short phoneType) {
        this.userId = userId;
        this.imei = imei;
        this.onlineMoney = onlineMoney;
        this.consumeKey = consumeKey;
        this.tacKey = tacKey;
        this.type = type;
        this.addTime = addTime;
        this.modTime = modTime;
        this.cardSeq = cardSeq;
        this.cardNo = cardNo;
        this.status = status;
        this.file15 = file15;
        this.file17 = file17;
        this.istest = istest;
        this.phonemodel = phonemodel;
        this.credit = credit;
        this.phoneType = phoneType;
    }

    @Id

    @Column(name = "user_id", unique = true, nullable = false, length = 64)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "imei", length = 64)
    public String getImei() {
        return this.imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    @Column(name = "online_money", nullable = false, length = 64)
    public String getOnlineMoney() {
        return this.onlineMoney;
    }

    public void setOnlineMoney(String onlineMoney) {
        this.onlineMoney = onlineMoney;
    }

    @Column(name = "consume_key", length = 64)
    public String getConsumeKey() {
        return this.consumeKey;
    }

    public void setConsumeKey(String consumeKey) {
        this.consumeKey = consumeKey;
    }

    @Column(name = "tac_key", length = 64)
    public String getTacKey() {
        return this.tacKey;
    }

    public void setTacKey(String tacKey) {
        this.tacKey = tacKey;
    }

    @Column(name = "type")
    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    @Column(name = "add_time", length = 64)
    public String getAddTime() {
        return this.addTime;
    }

    public void setAddTime(String addTime) {
        this.addTime = addTime;
    }

    @Column(name = "mod_time", length = 64)
    public String getModTime() {
        return this.modTime;
    }

    public void setModTime(String modTime) {
        this.modTime = modTime;
    }

    @Column(name = "card_seq", length = 8)
    public String getCardSeq() {
        return this.cardSeq;
    }

    public void setCardSeq(String cardSeq) {
        this.cardSeq = cardSeq;
    }

    @Column(name = "card_no", length = 32)
    public String getCardNo() {
        return this.cardNo;
    }

    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    @Column(name = "status")
    public Short getStatus() {
        return this.status;
    }

    public void setStatus(Short status) {
        this.status = status;
    }

    @Column(name = "file15", length = 256)
    public String getFile15() {
        return this.file15;
    }

    public void setFile15(String file15) {
        this.file15 = file15;
    }

    @Column(name = "file17", length = 256)
    public String getFile17() {
        return this.file17;
    }

    public void setFile17(String file17) {
        this.file17 = file17;
    }

    @Column(name = "istest")
    public Short getIstest() {
        return this.istest;
    }

    public void setIstest(Short istest) {
        this.istest = istest;
    }

    @Column(name = "phonemodel", length = 64)
    public String getPhonemodel() {
        return this.phonemodel;
    }

    public void setPhonemodel(String phonemodel) {
        this.phonemodel = phonemodel;
    }

    @Column(name = "credit")
    public Short getCredit() {
        return this.credit;
    }

    public void setCredit(Short credit) {
        this.credit = credit;
    }

    @Column(name = "phoneType")
    public Short getPhoneType() {
        return this.phoneType;
    }

    public void setPhoneType(Short phoneType) {
        this.phoneType = phoneType;
    }

}
