logging:
  file: ./sc00.log
  level:
    root: info
    cn: debug
server:
  port: 8080
spring:
  application:
    name: spring-cloud-eureka
  cloud:
    inetutils:
      ignored-interfaces: ethx
eureka:
  dashboard:
    enabled: true
    path: /
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/